### ISSUE TITLE
GUI tool?

### ISSUE THREAD

**Issue by Prid13** [cions/leveldb-cli#3]
God bless you, you beautiful soul! This is the first tool I've ever used after scouring the web for _years_ searching for _any_ tool that can realiably and easily show the raw contents of Chrome extension storage leveldb files without any werid bytes or other stuff showing up. No, this was as easily as downloading the release for Windows, copying and pasting the Chrome extension data files (found under `%LOCALAPPDATA%\Local\Google\Chrome\User Data\Default\Local Extension Settings\<extension-id>`), firing up CMD and simply typing `leveldb show`, that's it, and suddenly everything stored _exactly_ as it is saved was shown right to me 😭 Seriously, thank you for developing this, I am super happy right now :)

With that out of the way, are there any plans for a simple GUI to accompany this wonderful CLI? Since this is already so simple to use, a super simple GUI with simple browsing functionality would be the killer combo.

I'm still not over how well this is supporting Chrome data files, like wow. This _needs_ to be more visible when searching for tools to parse Chrome data files. If you don't have any plans, I'd love to make a GUI some time in the future :)

**Comment by cions** [comment]
Sorry, I have no plans to develop a GUI version as it is not what I need.

**Comment by Prid13** [comment]
No problem at all, I'm just super happy that this even exists and is so simple to use and just works 😇

You wouldn't mind if I created a GUI for this in the future, would you? :)
