### ISSUE TITLE
idb_cmp1 problems

### ISSUE THREAD

**Issue by mortinlojen3030** [cions/leveldb-cli#4]
when i try to get the keys like this:
leveldb -i keys

I'm getting such unreadable keys. what's wrong?

\0\0\0\0\0
\0\0\0\0\x01
\0\0\0\0\x02
\0\0\0\0\x05
\0\0\0\0\x06
\0\0\0\02\0
\0\0\0\0\xc95\0c\0h\0r\0o\0m\0e\0-\0e\0x\0t\0e\0n\0s\0i\0o\0n\0_\0a\0h\0o\0l\0p\0f\0d\0i\0a\0l\0j\0g\0j\0f\0h\0o\0m\0i\0h\0k\0j\0b\0m\0g\0j\0i\0d\0l\0c\0d\0n\0o\0_\00\0@\01\x16\0f\0i\0r\0e\0b\0a\0s\0e\0L\0o\0c\0a\0l\0S\0t\0o\0r\0a\0g\0e\0D\0b
\0\x01\0\0\x03
\0\x01\0\0\x04
\0\x01\0\0\x05
\0\x01\0\02\x01\0
\0\x01\0\02\x01\x01
\0\x01\0\02\x01\x02

**Comment by cions** [comment]
Because IndexedDB is stored on LevelDB in such a way.
https://chromium.googlesource.com/chromium/src/+/main/content/browser/indexed_db/docs/leveldb_coding_scheme.md

**Comment by Kovinda** [comment]
Is there a way to decode the data ?
